easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Product:
            class: App\Entity\Product
            label: 'Products'
            list:
                fields: ['id', 'name', { property: 'code', label: 'Product Code' }, 'createdAt', {property: 'status', type: 'toggle'}, 'category']
                title: "Most recent products"
                help: 'The list view overrides the global help message'
                max_results: 10
                sort: 'createdAt'
                dql_filter: 'entity.id > 1'
                actions: ['show']
                batch_actions: ['delete']
            new:
                title: "Add Products"
                fields:
                    - { property: 'name', icon: 'user' }
                    - { property: 'code', css_class: 'input-large', type_options: { required: false } }
                    - { property: 'category', type: 'easyadmin_autocomplete', type_options: { class: 'App\Entity\Category' } }
                    - { property: 'description', type: 'text_editor' }

        Category:
            class: App\Entity\Category
#        - App\Entity\User
    site_name: 'Test Backend'
    user:
        display_name: true
    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
        menu:
            - { entity: 'Product', css_class: 'menu--product text-bold text-center' }
            - { entity: 'Category', css_class: 'default' }
            - label: 'Products'
              children: ['Product', 'Category']
