sensio_framework_extra:
    router:
        annotations: false
    request:
        converters: false
        auto_convert: false
        disable: {  }
    view:
        annotations: false
    cache:
        annotations: false
